ruby_version: 3.3.2
ignore:
  - test/command/checkout_test.rb:
      - Style/RedundantStringEscape
  - test/command/status_test.rb:
      - Style/RedundantStringEscape
  - lib/diff/hunk.rb:
      - Lint/FormatParameterMismatch
